// Code generated by mockery v2.43.2. DO NOT EDIT.

package authenticator

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUsers is an autogenerated mock type for the Users type
type MockUsers struct {
	mock.Mock
}

type MockUsers_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsers) EXPECT() *MockUsers_Expecter {
	return &MockUsers_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, email, password
func (_m *MockUsers) Authenticate(ctx context.Context, email string, password string) (string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsers_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockUsers_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockUsers_Expecter) Authenticate(ctx interface{}, email interface{}, password interface{}) *MockUsers_Authenticate_Call {
	return &MockUsers_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, email, password)}
}

func (_c *MockUsers_Authenticate_Call) Run(run func(ctx context.Context, email string, password string)) *MockUsers_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUsers_Authenticate_Call) Return(_a0 string, _a1 error) *MockUsers_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsers_Authenticate_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockUsers_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// CheckExistence provides a mock function with given fields: ctx, email
func (_m *MockUsers) CheckExistence(ctx context.Context, email string) (bool, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for CheckExistence")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsers_CheckExistence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckExistence'
type MockUsers_CheckExistence_Call struct {
	*mock.Call
}

// CheckExistence is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUsers_Expecter) CheckExistence(ctx interface{}, email interface{}) *MockUsers_CheckExistence_Call {
	return &MockUsers_CheckExistence_Call{Call: _e.mock.On("CheckExistence", ctx, email)}
}

func (_c *MockUsers_CheckExistence_Call) Run(run func(ctx context.Context, email string)) *MockUsers_CheckExistence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUsers_CheckExistence_Call) Return(_a0 bool, _a1 error) *MockUsers_CheckExistence_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsers_CheckExistence_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockUsers_CheckExistence_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsers creates a new instance of MockUsers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsers {
	mock := &MockUsers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
